### PR TITLE
Update processdata.py for arima processing

### PR DESCRIPTION
**Pull request by meganemartinez**
Modificattions to load data as format expected by arima analysis

### CODE REVIEW

**Comment by rupchap** [comment]
Thanks Megane,  I've merged these in. but note that Artemis will be making bigger changes to process.py shortly [see slack]

**Comment by rupchap** [comment]
I've added similar changes to processandmerge

**Comment by meganemartinez** [comment]
Ok, but for arima I only need to load the load_history data with the
datetime in yyyy-mm-dd hh:mm:ss format, I don't need the temperature or any
other features

**Comment by rupchap** [comment]
Yes - although I think it does no harm with those columns being there?  just ignore them?

**Comment by rupchap** [comment]
your code runs fine on the new inputs

**Comment by meganemartinez** [comment]
Ok perfect then !

**Pull request merged**
